create table gtt_new.sgsnpdprecord (
    file_name string,
	accessPointNameNI	string,
	accessPointNameOI	string,
	apnSelectionMode	string,
	cAMELInformationPDPKey	string,
	causeForRecClosing	bigint,
	cellIdentifier	string,
	chargingCharacteristics	string,
	chargingID	bigint,
	chChSelectionMode	string,
	duration	bigint,
	dynamicAddressFlag	smallint,
	ggsnAddressUsed	string,
	`integer`	bigint,
	localSequenceNumber	bigint,
	locationAreaCode	string,
	msNetworkCapability	string,
	mSTimeZone	string,
	networkInitiation	smallint,
	nodeID	string,
	pdpType	string,
	pLMNIdentifier	string,
	rATType	bigint,
	recordExtensionsKey	string,
	recordOpeningTime	timestamp,
	recordSequenceNumber	bigint,
	recordType	bigint,
	routingArea	string,
	servedIMEI	string,
	servedIMSI	string,
	servedMSISDN	string,
	servedPDPAddress	string,
	sgsnAddress	string,
	sgsnChange	smallint,
	trafficVolumesKey string
)
partitioned by (timeframe_day bigint,
timeframe_hr int)
stored as parquet
location '/tmp/atni/data/sgsnpdprecord';
