# Auto-generated by asn1ate v.0.5.1.dev from ericsson_gprs.asn
# (last modified on 2016-05-05 09:12:28)
import sys

from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


class APNSelectionMode(univ.Enumerated):
    pass


APNSelectionMode.namedValues = namedval.NamedValues(
    ('mSorNetworkProvidedSubscriptionVerified', 0),
    ('mSProvidedSubscriptionNotVerified', 1),
    ('networkProvidedSubscriptionNotVerified', 2)
)


class AccessPointNameNI(char.IA5String):
    pass


AccessPointNameNI.subtypeSpec = constraint.ValueSizeConstraint(1, 63)


class AccessPointNameOI(char.IA5String):
    pass


AccessPointNameOI.subtypeSpec = constraint.ValueSizeConstraint(1, 37)


maxAddressLength = univ.Integer(20)


class AddressString(univ.OctetString):
    pass


AddressString.subtypeSpec = constraint.ValueSizeConstraint(1, maxAddressLength)


class BCDDirectoryNumber(univ.OctetString):
    pass


class CAMELAccessPointNameNI(AccessPointNameNI):
    pass


class CAMELAccessPointNameOI(AccessPointNameOI):
    pass


class NumberOfDPEncountered(univ.Integer):
    pass


class SCFAddress(AddressString):
    pass


class ServiceKey(univ.Integer):
    pass


ServiceKey.subtypeSpec = constraint.ValueRangeConstraint(0, 2147483647)


class FreeFormatData(univ.OctetString):
    pass


FreeFormatData.subtypeSpec = constraint.ValueSizeConstraint(1, 160)


class FFDAppendIndicator(univ.Boolean):
    pass


class DefaultGPRS_Handling(univ.Enumerated):
    pass


DefaultGPRS_Handling.namedValues = namedval.NamedValues(
    ('continueTransaction', 0),
    ('releaseTransaction', 1)
)


class LevelOfCAMELService(univ.BitString):
    pass


LevelOfCAMELService.namedValues = namedval.NamedValues(
    ('basic', 0),
    ('callDurationSupervision', 1),
    ('onlineCharging', 2)
)


class CAMELInformationPDP(univ.Set):
    pass


CAMELInformationPDP.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('sCFAddress', SCFAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('serviceKey', ServiceKey().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('defaultTransactionHandling', DefaultGPRS_Handling().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('cAMELAccessPointNameNI', CAMELAccessPointNameNI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('cAMELAccessPointNameOI', CAMELAccessPointNameOI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('numberOfDPEncountered', NumberOfDPEncountered().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('levelOfCAMELService', LevelOfCAMELService().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('freeFormatData', FreeFormatData().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('fFDAppendIndicator', FFDAppendIndicator().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9)))
)


class DefaultSMS_Handling(univ.Enumerated):
    pass


DefaultSMS_Handling.namedValues = namedval.NamedValues(
    ('continueTransaction', 0),
    ('releaseTransaction', 1)
)


class CallReferenceNumber(univ.OctetString):
    pass


CallReferenceNumber.subtypeSpec = constraint.ValueSizeConstraint(1, 8)


class CallingNumber(BCDDirectoryNumber):
    pass


class SmsTpDestinationNumber(univ.OctetString):
    pass


class CAMELInformationSMS(univ.Set):
    pass


CAMELInformationSMS.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('sCFAddress', SCFAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('serviceKey', ServiceKey().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('defaultSMSHandling', DefaultSMS_Handling().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('cAMELCallingPartyNumber', CallingNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('cAMELDestinationSubscriberNumber', SmsTpDestinationNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('cAMELSMSCAddress', AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('freeFormatData', FreeFormatData().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('smsReferenceNumber', CallReferenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8)))
)


class CallDuration(univ.Integer):
    pass


class CallEventRecordType(univ.Integer):
    pass


CallEventRecordType.namedValues = namedval.NamedValues(
    ('sgsnPDPRecord', 18),
    ('sgsnSMORecord', 21),
    ('sgsnSMTRecord', 22)
)


class ChChSelectionMode(univ.Enumerated):
    pass


ChChSelectionMode.namedValues = namedval.NamedValues(
    ('subscriptionSpecific', 1),
    ('aPNSpecific', 2),
    ('homeDefault', 3),
    ('roamingDefault', 4)
)


maxISDN_AddressLength = univ.Integer(9)


class ISDN_AddressString(AddressString):
    pass


class MSISDN(ISDN_AddressString):
    pass


class TimeStamp(univ.OctetString):
    pass


TimeStamp.subtypeSpec = constraint.ValueSizeConstraint(9, 9)


class NodeID(char.IA5String):
    pass


NodeID.subtypeSpec = constraint.ValueSizeConstraint(1, 20)


class LocationAreaCode(univ.OctetString):
    pass


LocationAreaCode.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class LocalSequenceNumber(univ.Integer):
    pass


LocalSequenceNumber.subtypeSpec = constraint.ValueRangeConstraint(0, 4294967295)


class Diagnostics(univ.Choice):
    pass


Diagnostics.componentType = namedtype.NamedTypes(
    namedtype.NamedType('gsm0408Cause', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('gsm0902MapErrorValue', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class SMSResult(Diagnostics):
    pass


class PLMN_Id(univ.OctetString):
    pass


PLMN_Id.subtypeSpec = constraint.ValueSizeConstraint(3, 3)


class RoutingAreaCode(univ.OctetString):
    pass


RoutingAreaCode.subtypeSpec = constraint.ValueSizeConstraint(1, 1)


class RecordingEntity(AddressString):
    pass


class TBCD_STRING(univ.OctetString):
    pass


class IMSI(TBCD_STRING):
    pass


class RATType(univ.Integer):
    pass


class IMEI(TBCD_STRING):
    pass


class ChargingCharacteristics(univ.OctetString):
    pass


ChargingCharacteristics.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class MSNetworkCapability(univ.OctetString):
    pass


MSNetworkCapability.subtypeSpec = constraint.ValueSizeConstraint(1, 8)


class CellId(univ.OctetString):
    pass


CellId.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class SGSNSMTRecord(univ.Set):
    pass


SGSNSMTRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', CallEventRecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('servedIMEI', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('msNetworkCapability', MSNetworkCapability().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('serviceCentre', AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('recordingEntity', RecordingEntity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('locationArea', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('cellIdentifier', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.NamedType('eventTimeStamp', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.OptionalNamedType('smsResult', SMSResult().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 11))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('numberOfSM', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 101))),
    namedtype.OptionalNamedType('locationAreaLastSM', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 102))),
    namedtype.OptionalNamedType('routingAreaLastSM', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 103))),
    namedtype.OptionalNamedType('cellIdentifierLastSM', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 104))),
    namedtype.OptionalNamedType('pLMNIdentifierLastSM', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 105))),
    namedtype.OptionalNamedType('pLMNIdentifier', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 106)))
)


class PDPType(univ.OctetString):
    pass


PDPType.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class DataVolumeGPRS(univ.Integer):
    pass


class QoSInformation(univ.OctetString):
    pass


QoSInformation.subtypeSpec = constraint.ValueSizeConstraint(4, 100)


class ChangeCondition(univ.Enumerated):
    pass


ChangeCondition.namedValues = namedval.NamedValues(
    ('qoSChange', 0),
    ('tariffTime', 1),
    ('recordClosure', 2)
)


class ChangeOfCharCondition(univ.Sequence):
    pass


ChangeOfCharCondition.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('qosRequested', QoSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('qosNegotiated', QoSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('dataVolumeGPRSUplink', DataVolumeGPRS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.NamedType('dataVolumeGPRSDownlink', DataVolumeGPRS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.NamedType('changeCondition', ChangeCondition().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.NamedType('changeTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6)))
)


class ETSIAddress(AddressString):
    pass


class IPTextRepresentedAddress(univ.Choice):
    pass


IPTextRepresentedAddress.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPTextV4Address', char.IA5String().subtype(subtypeSpec=constraint.ValueSizeConstraint(7, 15)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('iPTextV6Address', char.IA5String().subtype(subtypeSpec=constraint.ValueSizeConstraint(15, 45)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3)))
)


class IPBinaryAddress(univ.Choice):
    pass


IPBinaryAddress.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPBinV4Address', univ.OctetString().subtype(subtypeSpec=constraint.ValueSizeConstraint(4, 4)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('iPBinV6Address', univ.OctetString().subtype(subtypeSpec=constraint.ValueSizeConstraint(16, 16)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class IPAddress(univ.Choice):
    pass


IPAddress.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPBinaryAddress', IPBinaryAddress()),
    namedtype.NamedType('iPTextRepresentedAddress', IPTextRepresentedAddress())
)


class PDPAddress(univ.Choice):
    pass


PDPAddress.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPAddress', IPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0))),
    namedtype.NamedType('eTSIAddress', ETSIAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class GSNAddress(IPAddress):
    pass


class CauseForRecClosing(univ.Integer):
    pass


CauseForRecClosing.namedValues = namedval.NamedValues(
    ('normalRelease', 0),
    ('abnormalRelease', 4),
    ('cAMELInitCallRelease', 5),
    ('volumeLimit', 16),
    ('timeLimit', 17),
    ('sGSNChange', 18),
    ('maxChangeCond', 19),
    ('managementIntervention', 20),
    ('mSTimeZoneChange', 23),
    ('pLMNChange', 101)
)


class SGSNChange(univ.Boolean):
    pass


class DynamicAddressFlag(univ.Boolean):
    pass


class ExtendedDiagnostics(univ.Choice):
    pass


ExtendedDiagnostics.componentType = namedtype.NamedTypes(
    namedtype.NamedType('ts48018BssgpCause', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('ts25413RanapCause', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class GprsSCdrExtensions(univ.Set):
    pass


GprsSCdrExtensions.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('extendedDiagnostics', ExtendedDiagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0)))
)


class ManagementExtension(univ.Sequence):
    pass


ManagementExtension.componentType = namedtype.NamedTypes(
    namedtype.NamedType('identifier', univ.ObjectIdentifier()),
    namedtype.DefaultedNamedType('significance', univ.Boolean().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)).subtype(value=0)),
    namedtype.NamedType('information', GprsSCdrExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 2)))
)


class ManagementExtensions(univ.SetOf):
    pass


ManagementExtensions.componentType = ManagementExtension()


class ChargingID(univ.Integer):
    pass


ChargingID.subtypeSpec = constraint.ValueRangeConstraint(0, 4294967295)


class MSTimeZone(univ.OctetString):
    pass


MSTimeZone.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class SGSNPDPRecord(univ.Set):
    pass


SGSNPDPRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', CallEventRecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.OptionalNamedType('networkInitiation', univ.Boolean().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('servedIMEI', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('sgsnAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 5))),
    namedtype.OptionalNamedType('msNetworkCapability', MSNetworkCapability().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('locationAreaCode', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('cellIdentifier', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.NamedType('chargingID', ChargingID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.NamedType('ggsnAddressUsed', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 11))),
    namedtype.OptionalNamedType('accessPointNameNI', AccessPointNameNI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('pdpType', PDPType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.OptionalNamedType('servedPDPAddress', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 14))),
    namedtype.OptionalNamedType('listOfTrafficVolumes', univ.SequenceOf(componentType=ChangeOfCharCondition()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.NamedType('recordOpeningTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.NamedType('duration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('sgsnChange', SGSNChange().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 18))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 20))),
    namedtype.OptionalNamedType('recordSequenceNumber', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 21))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 22))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.OptionalNamedType('apnSelectionMode', APNSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25))),
    namedtype.OptionalNamedType('accessPointNameOI', AccessPointNameOI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 26))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 27))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 28))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 29))),
    namedtype.OptionalNamedType('cAMELInformationPDP', CAMELInformationPDP().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 30))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 32))),
    namedtype.OptionalNamedType('dynamicAddressFlag', DynamicAddressFlag().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 33))),
    namedtype.OptionalNamedType('pLMNIdentifier', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 101))),
    namedtype.OptionalNamedType('mSTimeZone', MSTimeZone().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 102)))
)


class MessageReference(univ.OctetString):
    pass


class SGSNSMORecord(univ.Set):
    pass


SGSNSMORecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', CallEventRecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('servedIMEI', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('msNetworkCapability', MSNetworkCapability().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('serviceCentre', AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('recordingEntity', RecordingEntity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('locationArea', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('cellIdentifier', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.NamedType('messageReference', MessageReference().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.NamedType('eventTimeStamp', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.OptionalNamedType('smsResult', SMSResult().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 12))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('destinationNumber', SmsTpDestinationNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 18))),
    namedtype.OptionalNamedType('cAMELInformationSMS', CAMELInformationSMS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 19))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 20))),
    namedtype.OptionalNamedType('pLMNIdentifier', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 101)))
)


class CallEventRecord(univ.Choice):
    pass


CallEventRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('sgsnPDPRecord', SGSNPDPRecord().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 20))),
    namedtype.NamedType('sgsnSMORecord', SGSNSMORecord().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 23))),
    namedtype.NamedType('sgsnSMTRecord', SGSNSMTRecord().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 24)))
)
