class ZTEUMTSStats:
    def __init__(self, iteration_id, file_id, file_name,  checksum, total_records, success_count, fail_count,
                 commonequip_base_total_count, commonequip_base_success_count, commonequip_base_failed_count,
                 incgateway_base_total_count, incgateway_base_success_count, incgateway_base_failed_count,
                 mcfcall_base_total_count, mcfcall_base_success_count, mcfcall_base_failed_count,
                 mocall_base_total_count, mocall_base_success_count, mocall_base_failed_count,
                 mosms_base_total_count, mosms_base_success_count, mosms_base_failed_count,
                 mtcall_base_total_count, mtcall_base_success_count, mtcall_base_failed_count,
                 mtlcs_base_total_count, mtlcs_base_success_count, mtlcs_base_failed_count,
                 mtsms_base_total_count, mtsms_base_success_count, mtsms_base_failed_count,
                 outgateway_base_total_count, outgateway_base_success_count, outgateway_base_failed_count,
                 ssaction_base_total_count, ssaction_base_success_count, ssaction_base_failed_count,
                 ussd_base_total_count, ussd_base_success_count, ussd_base_failed_count,
                 gsicph_base_total_count, gsicph_base_success_count, gsicph_base_failed_count,
                 hlrint_base_total_count, hlrint_base_success_count, hlrint_base_failed_count,
                 molcs_base_total_count, molcs_base_success_count, molcs_base_failed_count,
                 mtrf_base_total_count, mtrf_base_success_count, mtrf_base_failed_count,
                 ncscph_base_total_count, ncscph_base_success_count, ncscph_base_failed_count,
                 nilcs_base_total_count, nilcs_base_success_count, nilcs_base_failed_count,
                 vig_base_total_count, vig_base_success_count, vig_base_failed_count,
                 mcfcph_base_total_count, mcfcph_base_success_count, mcfcph_base_failed_count,
                 tcicph_base_total_count, tcicph_base_success_count, tcicph_base_failed_count,
                 mscsrvcc_base_total_count, mscsrvcc_base_success_count, mscsrvcc_base_failed_count,
                 roam_base_total_count, roam_base_success_count, roam_base_failed_count,
                 mocph_base_total_count, mocph_base_success_count, mocph_base_failed_count,
                 moecall_base_total_count, moecall_base_success_count, moecall_base_failed_count,
                 termcamelint_base_total_count, termcamelint_base_success_count, termcamelint_base_failed_count
                 ):
        self.file_name = file_name
        self.file_id = file_id
        self.iteration_id = iteration_id
        self.checksum = checksum
        self.total_records = total_records
        self.success_count = success_count
        self.fail_count = fail_count
        self.commonequip_base_total_count = commonequip_base_total_count
        self.commonequip_base_success_count = commonequip_base_success_count
        self.commonequip_base_failed_count = commonequip_base_failed_count
        self.incgateway_base_total_count = incgateway_base_total_count
        self.incgateway_base_success_count = incgateway_base_success_count
        self.incgateway_base_failed_count = incgateway_base_failed_count
        self.mcfcall_base_total_count = mcfcall_base_total_count
        self.mcfcall_base_success_count = mcfcall_base_success_count
        self.mcfcall_base_failed_count = mcfcall_base_failed_count
        self.mocall_base_total_count = mocall_base_total_count
        self.mocall_base_success_count = mocall_base_success_count
        self.mocall_base_failed_count = mocall_base_failed_count
        self.mosms_base_total_count = mosms_base_total_count
        self.mosms_base_success_count = mosms_base_success_count
        self.mosms_base_failed_count = mosms_base_failed_count
        self.mtcall_base_total_count = mtcall_base_total_count
        self.mtcall_base_success_count = mtcall_base_success_count
        self.mtcall_base_failed_count = mtcall_base_failed_count
        self.mtlcs_base_total_count = mtlcs_base_total_count
        self.mtlcs_base_success_count = mtlcs_base_success_count
        self.mtlcs_base_failed_count = mtlcs_base_failed_count
        self.mtsms_base_total_count = mtsms_base_total_count
        self.mtsms_base_success_count = mtsms_base_success_count
        self.mtsms_base_failed_count = mtsms_base_failed_count
        self.outgateway_base_total_count = outgateway_base_total_count
        self.outgateway_base_success_count = outgateway_base_success_count
        self.outgateway_base_failed_count = outgateway_base_failed_count
        self.ssaction_base_total_count = ssaction_base_total_count
        self.ssaction_base_success_count = ssaction_base_success_count
        self.ssaction_base_failed_count = ssaction_base_failed_count
        self.ussd_base_total_count = ussd_base_total_count
        self.ussd_base_success_count = ussd_base_success_count
        self.ussd_base_failed_count = ussd_base_failed_count
        self.gsicph_base_total_count = gsicph_base_total_count
        self.gsicph_base_success_count = gsicph_base_success_count
        self.gsicph_base_failed_count = gsicph_base_failed_count
        self.hlrint_base_total_count = hlrint_base_total_count
        self.hlrint_base_success_count = hlrint_base_success_count
        self.hlrint_base_failed_count = hlrint_base_failed_count
        self.molcs_base_total_count = molcs_base_total_count
        self.molcs_base_success_count = molcs_base_success_count
        self.molcs_base_failed_count = molcs_base_failed_count
        self.mtrf_base_total_count = mtrf_base_total_count
        self.mtrf_base_success_count = mtrf_base_success_count
        self.mtrf_base_failed_count = mtrf_base_failed_count
        self.ncscph_base_total_count = ncscph_base_total_count
        self.ncscph_base_success_count = ncscph_base_success_count
        self.ncscph_base_failed_count = ncscph_base_failed_count
        self.nilcs_base_total_count = nilcs_base_total_count
        self.nilcs_base_success_count = nilcs_base_success_count
        self.nilcs_base_failed_count = nilcs_base_failed_count
        self.vig_base_total_count = vig_base_total_count
        self.vig_base_success_count = vig_base_success_count
        self.vig_base_failed_count = vig_base_failed_count
        self.mcfcph_base_total_count = mcfcph_base_total_count
        self.mcfcph_base_success_count = mcfcph_base_success_count
        self.mcfcph_base_failed_count = mcfcph_base_failed_count
        self.tcicph_base_total_count = tcicph_base_total_count
        self.tcicph_base_success_count = tcicph_base_success_count
        self.tcicph_base_failed_count = tcicph_base_failed_count
        self.mscsrvcc_base_total_count = mscsrvcc_base_total_count
        self.mscsrvcc_base_success_count = mscsrvcc_base_success_count
        self.mscsrvcc_base_failed_count = mscsrvcc_base_failed_count
        self.roam_base_total_count = roam_base_total_count
        self.roam_base_success_count = roam_base_success_count
        self.roam_base_failed_count = roam_base_failed_count
        self.mocph_base_total_count = mocph_base_total_count
        self.mocph_base_success_count = mocph_base_success_count
        self.mocph_base_failed_count = mocph_base_failed_count
        self.moecall_base_total_count = moecall_base_total_count
        self.moecall_base_success_count = moecall_base_success_count
        self.moecall_base_failed_count = moecall_base_failed_count
        self.termcamelint_base_total_count = termcamelint_base_total_count
        self.termcamelint_base_success_count = termcamelint_base_success_count
        self.termcamelint_base_failed_count = termcamelint_base_failed_count



